---
abstract: 'Generate function (and its spec) to read table data'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-Gen-ReadTable
requires:
  Data::Sah::Util: 0
  Lingua::EN::Numbers: 0
  Lingua::ID::Nums2Words: 0
  Sub::Spec: 0.15
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-Gen-ReadTable/
  repository: http://github.com/sharyanto/perl-Sub-Spec-Gen-ReadTable
version: 0.04
